version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      ENV MYSQL_ROOT_PASSWORD: 1234
      ENV MYSQL_DATABASE: DB_prueba
      ENV MYSQL_USER: user
      ENV MYSQL_PASSWORD: 123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/
